
create database MyWebsite;
use MyWebsite;

create table MOVIES(
MOVIE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(200),
YEAR INT,
DURATION DOUBLE,
RELEASE_DATE DATETIME,
CAST_COUNT INT,
STATUS CHAR,
CREATED_DATE DATETIME
);

insert into movies values (1,'Test 1','2006','123.0',now(),'3','A',now());

CREATE TABLE GENRE(
GENRE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
VALUE VARCHAR(200),
STATUS CHAR,
CREATED_DATE DATETIME
);

CREATE TABLE DIRECTORS(
DIRECTORS_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(200),
STATUS CHAR,
CREATED_DATE DATETIME
);

CREATE TABLE PRODUCERS(
PRODUCERS_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(200),
STATUS CHAR,
CREATED_DATE DATETIME
);

CREATE TABLE STARS(
STARS_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(200),
STATUS CHAR,
CREATED_DATE DATETIME
);

CREATE TABLE MOVIE_GENERE(
MOVIE_GENERE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
MOVIE_ID BIGINT ,
GENRE_ID BIGINT,
STATUS CHAR,
CREATED_DATE DATETIME,
FOREIGN KEY FK_MOVIES(MOVIE_ID) REFERENCES MOVIES(MOVIE_ID),
FOREIGN KEY FK_GENRE(GENRE_ID) REFERENCES GENRE(GENRE_ID)
);

CREATE TABLE MOVIE_DIRECTORS(
MOVIE_DIRECTORS_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
MOVIE_ID BIGINT ,
DIRECTORS_ID BIGINT ,
STATUS CHAR,
CREATED_DATE DATETIME,
FOREIGN KEY FK_MOVIES(MOVIE_ID) REFERENCES MOVIES(MOVIE_ID),
FOREIGN KEY FK_DIRECTORS(DIRECTORS_ID) REFERENCES DIRECTORS(DIRECTORS_ID)

);

CREATE TABLE MOVIE_PRODUCERS(
MOVIE_PRODUCERS_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
MOVIE_ID BIGINT ,
PRODUCERS_ID BIGINT,
STATUS CHAR,
CREATED_DATE DATETIME,
FOREIGN KEY FK_MOVIES(MOVIE_ID) REFERENCES MOVIES(MOVIE_ID),
FOREIGN KEY FK_PRODUCERS(PRODUCERS_ID) REFERENCES PRODUCERS(PRODUCERS_ID)
);

CREATE TABLE MOVIE_STARS(
MOVIE_CAST_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
MOVIE_ID BIGINT ,
STARS_ID BIGINT,
STATUS CHAR,
CREATED_DATE DATETIME,
FOREIGN KEY FK_MOVIES(MOVIE_ID) REFERENCES MOVIES(MOVIE_ID),
FOREIGN KEY FK_STARS(STARS_ID) REFERENCES STARS(STARS_ID)
);

CREATE TABLE MOVIE_PLOT(
MOVIE_PLOT_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
MOVIE_ID BIGINT ,
PLOT VARCHAR(5000),
ROW_NUM INT,
STATUS CHAR,
CREATED_DATE DATETIME,
FOREIGN KEY FK_MOVIES(MOVIE_ID) REFERENCES MOVIES(MOVIE_ID)
);

CREATE TABLE MOVIE_SIMILAR(
MOVIE_SIMILAR_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
MOVIE_ID BIGINT  ,
SIMILAR_MOVIE_ID BIGINT  ,
STATUS CHAR,
CREATED_DATE DATETIME,
FOREIGN KEY FK_MOVIES(MOVIE_ID) REFERENCES MOVIES(MOVIE_ID),
FOREIGN KEY FK_MOVIES_SIMILAR(SIMILAR_MOVIE_ID) REFERENCES MOVIES(MOVIE_ID)
);
