package com.crud.rest.beans;
// Generated May 26, 2017 2:03:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name="genre"
    ,catalog="mywebsite"
)
public class Genre  implements java.io.Serializable {


     private Long genreId;
     private String value;
     private Character status;
     private Date createdDate;
     private Set<MovieGenere> movieGeneres = new HashSet<MovieGenere>(0);

    public Genre() {
    }

    public Genre(String value, Character status, Date createdDate, Set<MovieGenere> movieGeneres) {
       this.value = value;
       this.status = status;
       this.createdDate = createdDate;
       this.movieGeneres = movieGeneres;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="GENRE_ID", unique=true, nullable=false)
    public Long getGenreId() {
        return this.genreId;
    }
    
    public void setGenreId(Long genreId) {
        this.genreId = genreId;
    }

    
    @Column(name="VALUE", length=200)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="genre")
    public Set<MovieGenere> getMovieGeneres() {
        return this.movieGeneres;
    }
    
    public void setMovieGeneres(Set<MovieGenere> movieGeneres) {
        this.movieGeneres = movieGeneres;
    }




}


