package com.crud.rest.beans;
// Generated May 26, 2017 2:03:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovieDirectors generated by hbm2java
 */
@Entity
@Table(name="movie_directors"
    ,catalog="mywebsite"
)
public class MovieDirectors  implements java.io.Serializable {


     private Long movieDirectorsId;
     private Directors directors;
     private Movies movies;
     private Character status;
     private Date createdDate;

    public MovieDirectors() {
    }

    public MovieDirectors(Directors directors, Movies movies, Character status, Date createdDate) {
       this.directors = directors;
       this.movies = movies;
       this.status = status;
       this.createdDate = createdDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MOVIE_DIRECTORS_ID", unique=true, nullable=false)
    public Long getMovieDirectorsId() {
        return this.movieDirectorsId;
    }
    
    public void setMovieDirectorsId(Long movieDirectorsId) {
        this.movieDirectorsId = movieDirectorsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DIRECTORS_ID")
    public Directors getDirectors() {
        return this.directors;
    }
    
    public void setDirectors(Directors directors) {
        this.directors = directors;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MOVIE_ID")
    public Movies getMovies() {
        return this.movies;
    }
    
    public void setMovies(Movies movies) {
        this.movies = movies;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


