package com.crud.rest.beans;
// Generated May 26, 2017 2:03:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovieProducers generated by hbm2java
 */
@Entity
@Table(name="movie_producers"
    ,catalog="mywebsite"
)
public class MovieProducers  implements java.io.Serializable {


     private Long movieProducersId;
     private Movies movies;
     private Producers producers;
     private Character status;
     private Date createdDate;

    public MovieProducers() {
    }

    public MovieProducers(Movies movies, Producers producers, Character status, Date createdDate) {
       this.movies = movies;
       this.producers = producers;
       this.status = status;
       this.createdDate = createdDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MOVIE_PRODUCERS_ID", unique=true, nullable=false)
    public Long getMovieProducersId() {
        return this.movieProducersId;
    }
    
    public void setMovieProducersId(Long movieProducersId) {
        this.movieProducersId = movieProducersId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MOVIE_ID")
    public Movies getMovies() {
        return this.movies;
    }
    
    public void setMovies(Movies movies) {
        this.movies = movies;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCERS_ID")
    public Producers getProducers() {
        return this.producers;
    }
    
    public void setProducers(Producers producers) {
        this.producers = producers;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


