package com.crud.rest.beans;
// Generated May 26, 2017 2:03:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovieSimilar generated by hbm2java
 */
@Entity
@Table(name="movie_similar"
    ,catalog="mywebsite"
)
public class MovieSimilar  implements java.io.Serializable {


     private Long movieSimilarId;
     private Movies moviesBySimilarMovieId;
     private Movies moviesByMovieId;
     private Character status;
     private Date createdDate;

    public MovieSimilar() {
    }

    public MovieSimilar(Movies moviesBySimilarMovieId, Movies moviesByMovieId, Character status, Date createdDate) {
       this.moviesBySimilarMovieId = moviesBySimilarMovieId;
       this.moviesByMovieId = moviesByMovieId;
       this.status = status;
       this.createdDate = createdDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MOVIE_SIMILAR_ID", unique=true, nullable=false)
    public Long getMovieSimilarId() {
        return this.movieSimilarId;
    }
    
    public void setMovieSimilarId(Long movieSimilarId) {
        this.movieSimilarId = movieSimilarId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SIMILAR_MOVIE_ID")
    public Movies getMoviesBySimilarMovieId() {
        return this.moviesBySimilarMovieId;
    }
    
    public void setMoviesBySimilarMovieId(Movies moviesBySimilarMovieId) {
        this.moviesBySimilarMovieId = moviesBySimilarMovieId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MOVIE_ID")
    public Movies getMoviesByMovieId() {
        return this.moviesByMovieId;
    }
    
    public void setMoviesByMovieId(Movies moviesByMovieId) {
        this.moviesByMovieId = moviesByMovieId;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


