package com.crud.rest.beans;
// Generated May 26, 2017 2:03:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MoviePlot generated by hbm2java
 */
@Entity
@Table(name="movie_plot"
    ,catalog="mywebsite"
)
public class MoviePlot  implements java.io.Serializable {


     private Long moviePlotId;
     private Movies movies;
     private String plot;
     private Integer rowNum;
     private Character status;
     private Date createdDate;

    public MoviePlot() {
    }

    public MoviePlot(Movies movies, String plot, Integer rowNum, Character status, Date createdDate) {
       this.movies = movies;
       this.plot = plot;
       this.rowNum = rowNum;
       this.status = status;
       this.createdDate = createdDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MOVIE_PLOT_ID", unique=true, nullable=false)
    public Long getMoviePlotId() {
        return this.moviePlotId;
    }
    
    public void setMoviePlotId(Long moviePlotId) {
        this.moviePlotId = moviePlotId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MOVIE_ID")
    public Movies getMovies() {
        return this.movies;
    }
    
    public void setMovies(Movies movies) {
        this.movies = movies;
    }

    
    @Column(name="PLOT", length=5000)
    public String getPlot() {
        return this.plot;
    }
    
    public void setPlot(String plot) {
        this.plot = plot;
    }

    
    @Column(name="ROW_NUM")
    public Integer getRowNum() {
        return this.rowNum;
    }
    
    public void setRowNum(Integer rowNum) {
        this.rowNum = rowNum;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


