package com.crud.rest.beans;
// Generated May 26, 2017 2:03:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Producers generated by hbm2java
 */
@Entity
@Table(name="producers"
    ,catalog="mywebsite"
)
public class Producers  implements java.io.Serializable {


     private Long producersId;
     private String name;
     private Character status;
     private Date createdDate;
     private Set<MovieProducers> movieProducerses = new HashSet<MovieProducers>(0);

    public Producers() {
    }

    public Producers(String name, Character status, Date createdDate, Set<MovieProducers> movieProducerses) {
       this.name = name;
       this.status = status;
       this.createdDate = createdDate;
       this.movieProducerses = movieProducerses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PRODUCERS_ID", unique=true, nullable=false)
    public Long getProducersId() {
        return this.producersId;
    }
    
    public void setProducersId(Long producersId) {
        this.producersId = producersId;
    }

    
    @Column(name="NAME", length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producers")
    public Set<MovieProducers> getMovieProducerses() {
        return this.movieProducerses;
    }
    
    public void setMovieProducerses(Set<MovieProducers> movieProducerses) {
        this.movieProducerses = movieProducerses;
    }




}


