package com.crud.rest.beans;
// Generated May 26, 2017 2:03:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stars generated by hbm2java
 */
@Entity
@Table(name="stars"
    ,catalog="mywebsite"
)
public class Stars  implements java.io.Serializable {


     private Long starsId;
     private String name;
     private Character status;
     private Date createdDate;
     private Set<MovieStars> movieStarses = new HashSet<MovieStars>(0);

    public Stars() {
    }

    public Stars(String name, Character status, Date createdDate, Set<MovieStars> movieStarses) {
       this.name = name;
       this.status = status;
       this.createdDate = createdDate;
       this.movieStarses = movieStarses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="STARS_ID", unique=true, nullable=false)
    public Long getStarsId() {
        return this.starsId;
    }
    
    public void setStarsId(Long starsId) {
        this.starsId = starsId;
    }

    
    @Column(name="NAME", length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="STATUS", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stars")
    public Set<MovieStars> getMovieStarses() {
        return this.movieStarses;
    }
    
    public void setMovieStarses(Set<MovieStars> movieStarses) {
        this.movieStarses = movieStarses;
    }




}


